language: python
python:
- '2.6'
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
- pip install .
script:
 - script/validate-dco
 - flake8 fig
 - nosetests tests/unit
